### ISSUE TITLE
Repeating output

### ISSUE THREAD

**Issue by spockers** [RustyBower/sopel-weather#3]
I just started getting output like this: https://i.imgur.com/T6oilYI.png

 Latest version.

**Comment by RustyBower** [comment]
Interesting. What version of Sopel are you using?

**Comment by RustyBower** [comment]
Any other modules or config changes in the default.cfg?

**Comment by RustyBower** [comment]
Also, did you remove the old weather.py module from the modules folder?

**Comment by spockers** [comment]
I did have the original module, doh. I thought I'd overwritten it, but somehow I'd put it in a different folder. So far, so good.

Thanks!

**Comment by RustyBower** [comment]
No worries! Glad it's working :)

I should change some of the output to not conflate the previous version of the code versus this module.
