### ISSUE TITLE
api

### ISSUE THREAD

**Issue by spockers** [RustyBower/sopel-weather#5]
Could you use the Dark Sky API (https://darksky.net/dev/)? It seems to have a lot more locations than the open weather one. If not, no worries, thanks!

**Comment by RustyBower** [comment]
I’ll take a peek at it and see if it’ll work. Ideally I would like to specify a variety of API sources, so users could choose.

**Comment by RustyBower** [comment]
Looks like you have to pass in a latitude/longitude (which they don't have an ability to look up), which is a fundamental break from how the module currently works.

**Comment by RustyBower** [comment]
Echoing back on this. I am currently adding a few other weather sources.
