### ISSUE TITLE
Feature request : UV-index

### ISSUE THREAD

**Issue by erikpi** [RustyBower/sopel-weather#7]
Hello,
In these sunny times it would be nice with a UV-index for the .weather 
Is this possible to add? 

I cant see it on the openweathermap.com but I think the data is there.

Thanks in advance for a great module 😊

**Comment by RustyBower** [comment]
Unfortunately, i don't see anything in openweathermap.com for UV Index. But I am looking at some additional functionality from other APIs, so I'll leave this issue and comment back on it when that's ready

**Comment by RustyBower** [comment]
Found a place where I can get uv-index data. Working implementing it now with the DarkSky overhaul that I am doing

**Comment by dgw** [comment]
@RustyBower Maybe this is a new thing in OWM's API, but they appear to provide UV Index info now: https://openweathermap.org/api/uvi (and it's even included in the Free tier).

**Comment by RustyBower** [comment]
Yeah. I need to change this anyways to do GeoID lookups instead.

**Comment by RustyBower** [comment]
This is all finished. Let me know @erikpi

**Comment by erikpi** [comment]
It works! 
Thanks a lot ❤
