### ISSUE TITLE
Feature: Longer-term forecast

### ISSUE THREAD

**Issue by dgw** [RustyBower/sopel-weather#8]
Decided to have a poke at this plugin because my network's own service bot was giving bad forecast data. I expected a longer-term forecast than 24 hours, and it's not out of the question to implement that with OpenWeatherMap's free tier.

The [code for Rizon's Internets weather forecast](https://gitlab.com/rizon/acid/-/blob/5b7f8b9e745f4c5e4b60635672fc51eb396a4d59/pyva/pyva/src/main/python/internets/api/weather.py#L120-194) command might help? That's the very same forecast command that returned bad data and motivated me to try this plugin, though, but it could at least show an example. And if the bad data is OWM's fault—a bug in the API—then it'll work fine once fixed.

Feel free to punt this right back at me if you don't want to deal with it. I'd be happy to make a PR if that's what it takes to make this feature happen. 😸

**Comment by RustyBower** [comment]
Right now .forecast has been updated with temps for the next 24h, but it grab's the ~weekly summary from DarkSky (Light rain on Tuesday through next Saturday).

Let me know if that's what your looking for, otherwise PRs are welcome :)

**Comment by RustyBower** [comment]
Example Forecast - 
Minneapolis, MN, USA :: Saturday Scattered Clouds 2C / 35F 0C / 31F :: Sunday Broken Clouds 2C / 36F 0C / 33F :: Monday Broken Clouds 1C / 34F 0C / 32F :: Tuesday Overcast Clouds 0C / 32F 0C / 31F

**Comment by RustyBower** [comment]
Should be fixed in https://github.com/RustyBower/sopel-weather/commit/da95d1534c9ccbdbfd202a66a64ba22f2061804f
